CREATE TABLE usuarios (
    id    BIGSERIAL    PRIMARY KEY,
    login VARCHAR(100) NOT NULL UNIQUE,
    senha VARCHAR(255) NOT NULL,
    papel VARCHAR(20)  NOT NULL CHECK (papel IN ('ADMINISTRADOR', 'RECEPCIONISTA', 'MEDICO'))
);
