spring.application.name=es_clinic_project

#Banco de Dados
spring.datasource.url=jdbc:postgresql://localhost:5432/ES_clinica_bd
spring.datasource.username=user_clinica
spring.datasource.password=papaestc
spring.jpa.hibernate.ddl-auto=validate

#JWT
api.security.token.secret=clinica-medica-secret-dev

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
