spring.application.name=es_clinic_project

#Banco de Dados
spring.datasource.url=jdbc:postgresql://localhost:5432/ES_clinica_bd
spring.datasource.username=${DB_USERNAME:postgre}
spring.datasource.password=${DB_PASSWORD:postgrew}
spring.jpa.hibernate.ddl-auto=validate

#JWT
api.security.token.secret=${JWT_SECRET:clinica-medica-secret-dev}
