spring.application.name=es_clinic_project

#Banco de Dados
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ES_clinica_bd}
spring.datasource.username=${DB_USERNAME:user_clinica}
spring.datasource.password=${DB_PASSWORD:papaestc}
spring.jpa.hibernate.ddl-auto=validate

#JWT
api.security.token.secret=${JWT_SECRET:clinica-medica-secret-dev}

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
